
name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v3
        with:
          path: "~/Downloads"
          key: ${{ runner.os }}-runtimes-downloads-16.4        
      - name: Install Xcodes
        shell: bash
        run: |
          brew install aria2
          brew tap robotsandpencils/made
          brew install robotsandpencils/made/xcodes
          xcodes install --latest
      - name: Install Simulator
        shell: bash
        run: sudo xcodes runtimes install --keep-archive 'iOS 16.4'

      - name: UnitTests
        run: |
          xcodebuild test \
            -project UnitTestApp01.xcodeproj \
            -scheme UnitTestApp01 \
            -configuration Debug \
            -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 14' \
            -sdk iphonesimulator


